spring.application.name=PhegnHotel
server.port=4040

# PostgreSQL (Neon Database)
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-solitary-rice-aq56jbcr.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require}
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_q6Ry3apugOEk}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


cloudinary.cloud_name=danut2jn3
cloudinary.api_key=492848144572255
cloudinary.api_secret=6IiLz1eeJTkv_S1MJ78u4uA3GJo
